/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.*;
import java.util.*;
import Controlador.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author profe
 */
public class Resultado extends javax.swing.JFrame {

    Par<Integer, ArrayList<Par<Integer, Integer>>> parIdeal;
    Par<Integer, ArrayList<Par<Integer, Integer>>> parReal;
    ArrayList<Modulo> modulos;

    /**
     * Creates new form Resultado
     */
    public Resultado(Par<Integer, ArrayList<Par<Integer, Integer>>> parIdeal,
            Par<Integer, ArrayList<Par<Integer, Integer>>> parReal,
            ArrayList<Modulo> modulos) {
        this.parIdeal = parIdeal;
        this.parReal = parReal;
        this.modulos = modulos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    String[] optToArray(ArrayList<Par<Integer, Integer>> lista) {
        String[] res = new String[lista.size()];
        for (int i = 0; i < lista.size(); i++) {
            res[i] = modulos.get(lista.get(i).first).nombre;
        }
        return res;
    }

    void mostrarMejora(String mejora, String titulo) {
        //Lanzar el jdialog que muestra la mejora:
        txtAreaMejoras.setColumns(20);
        txtAreaMejoras.setRows(10);
        txtAreaMejoras.append(mejora);
        txtNombreMejora.setText(titulo);
        jDialogMejora.setLocationRelativeTo(null);
        jDialogMejora.setSize(500, 300);
        jDialogMejora.setVisible(true);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jDialogMejora = new javax.swing.JDialog();
        txtNombreMejora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaMejoras = new javax.swing.JTextArea();
        txtResultadosTitulo = new javax.swing.JLabel();
        txtResultadosTitulo1 = new javax.swing.JLabel();
        txtResultadosTitulo2 = new javax.swing.JLabel();
        txtResultadosTitulo3 = new javax.swing.JLabel();
        txtResultadosTitulo4 = new javax.swing.JLabel();
        txtResultadosTitulo5 = new javax.swing.JLabel();
        maximoFlujoIdeal = new javax.swing.JLabel();
        maximoFlujoReal = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listIdeal = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        listReal = new javax.swing.JList<>();

        jDialogMejora.setModal(true);
        jDialogMejora.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Limpia el JTextArea cuando se cierra el JDialog
                txtAreaMejoras.setText("");
                txtNombreMejora.setText("");
            }
        });

        txtNombreMejora.setFont(new java.awt.Font("Cascadia Code", 1, 24)); // NOI18N
        txtNombreMejora.setText("Nombre");

        txtAreaMejoras.setColumns(20);
        txtAreaMejoras.setFont(new java.awt.Font("Cascadia Code", 0, 14)); // NOI18N
        txtAreaMejoras.setRows(5);
        jScrollPane1.setViewportView(txtAreaMejoras);

        javax.swing.GroupLayout jDialogMejoraLayout = new javax.swing.GroupLayout(jDialogMejora.getContentPane());
        jDialogMejora.getContentPane().setLayout(jDialogMejoraLayout);
        jDialogMejoraLayout.setHorizontalGroup(
            jDialogMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMejoraLayout.createSequentialGroup()
                .addGroup(jDialogMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogMejoraLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogMejoraLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(txtNombreMejora)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jDialogMejoraLayout.setVerticalGroup(
            jDialogMejoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogMejoraLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtNombreMejora, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtResultadosTitulo.setFont(new java.awt.Font("Cascadia Code", 0, 24)); // NOI18N
        txtResultadosTitulo.setText("Resultados del calculo");

        txtResultadosTitulo1.setFont(new java.awt.Font("Cascadia Code", 0, 24)); // NOI18N
        txtResultadosTitulo1.setText("para la optimizacion");

        txtResultadosTitulo2.setFont(new java.awt.Font("Cascadia Code", 0, 24)); // NOI18N
        txtResultadosTitulo2.setText("Situacion real:");

        txtResultadosTitulo3.setFont(new java.awt.Font("Cascadia Code", 0, 24)); // NOI18N
        txtResultadosTitulo3.setText("Situacion ideal:");

        txtResultadosTitulo4.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        txtResultadosTitulo4.setText("Cant max de productos generados:");

        txtResultadosTitulo5.setFont(new java.awt.Font("Cascadia Code", 0, 12)); // NOI18N
        txtResultadosTitulo5.setText("Cant max de productos generados:");

        maximoFlujoIdeal.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        maximoFlujoIdeal.setText("a");
        maximoFlujoIdeal.setText(parIdeal.first + "");

        maximoFlujoReal.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
        maximoFlujoReal.setText("a");
        maximoFlujoReal.setText(parReal.first + "");

        listIdeal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listIdeal.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        listIdeal.setModel(new javax.swing.DefaultListModel<String>() {
            String[] strings = optToArray(parIdeal.second);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listIdeal.setToolTipText("Detalles (Doble Click)");

        listIdeal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        listIdeal.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int index = listIdeal.locationToIndex(evt.getPoint());
                    if (index >= 0) {
                        String item = listIdeal.getModel().getElementAt(index);
                        Modulo mod = getModuloAt(item);
                        String mejora = calcularMejora(mod.index);
                        //Lanzar el jdialog que usa esto
                        mostrarMejora(mejora, item);
                    }
                }
            }
        });
        jScrollPane3.setViewportView(listIdeal);

        listReal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listReal.setFont(new java.awt.Font("Cascadia Code", 1, 18)); // NOI18N
        listReal.setModel(new javax.swing.DefaultListModel<String>() {
            String[] strings = optToArray(parIdeal.second);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listReal.setToolTipText("Detalles (Doble Click)");

        listReal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        listReal.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    int index = listReal.locationToIndex(evt.getPoint());
                    if (index >= 0) {
                        String item = listReal.getModel().getElementAt(index);
                        Modulo mod = getModuloAt(item);
                        String mejora = calcularMejora(mod.index);
                        //Lanzar el jdialog que usa esto
                        mostrarMejora(mejora, item);
                    }
                }
            }
        });
        jScrollPane4.setViewportView(listReal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtResultadosTitulo1)
                        .addGap(229, 229, 229))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtResultadosTitulo)
                        .addGap(214, 214, 214))))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResultadosTitulo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(txtResultadosTitulo2)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtResultadosTitulo4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(maximoFlujoIdeal)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtResultadosTitulo5)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(maximoFlujoReal)
                                    .addGap(50, 50, 50)))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtResultadosTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultadosTitulo1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResultadosTitulo3)
                    .addComponent(txtResultadosTitulo2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtResultadosTitulo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(maximoFlujoIdeal))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(maximoFlujoReal))
                        .addComponent(txtResultadosTitulo5)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    Modulo getModuloAt(String nom) {
        for (Modulo mod : modulos) {
            if (nom.equals(mod.nombre)) {
                return mod;
            }
        }
        return null;
    }

    String calcularMejora(int index) {
        String res = "";
        ArrayList<String> mejoras = new ArrayList<String>();
        Modulo mod = modulos.get(index);
        if (mod.habilidad < 0.5) {
            mejoras.add("Puedes considerar que a este modulo se mejore la eficiencia de los empleados");
        } else {
            mejoras.add("Puedes considerar que a este modulo se le aumente la cantidad de empleados");
        }
        mejoras.add("Este modulo tiene una perdida bastante significativa, comete el error de: " + (mod.factorError * 100) + " considera mejorar la calidad de las maquinas o aplicar otro tipo de mejora para reducir el error en este modulo");
        for (String mejora : mejoras) {
            res += mejora + "\n";
        }
        return res;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialogMejora;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> listIdeal;
    private javax.swing.JList<String> listReal;
    private javax.swing.JLabel maximoFlujoIdeal;
    private javax.swing.JLabel maximoFlujoReal;
    private javax.swing.JTextArea txtAreaMejoras;
    private javax.swing.JLabel txtNombreMejora;
    private javax.swing.JLabel txtResultadosTitulo;
    private javax.swing.JLabel txtResultadosTitulo1;
    private javax.swing.JLabel txtResultadosTitulo2;
    private javax.swing.JLabel txtResultadosTitulo3;
    private javax.swing.JLabel txtResultadosTitulo4;
    private javax.swing.JLabel txtResultadosTitulo5;
    // End of variables declaration//GEN-END:variables
}
